spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.user_service.dto"
        spring.json.value.default.type: com.example.notification_service.dto.UserRegisteredEvent

  mail:
    host: smtp.gmail.com
    port: 587
    username: tranminhtien41001@gmail.com
    password: tfhl zmku ixtw rggk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true