server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/books/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8086/realm/book-management-realm
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
