server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user-book-store
    username: postgres
    password: '04102001'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8086/realm/book-management-realm
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

#jwt:
#  secret: daylakhoabaomatjwtcuatoitoiphaivietnhuthenaydedudodai
#  expiration: 86400000

keycloak:
  auth-server-url: http://localhost:8086
  base-url: http://localhost:8086
  realm-book: book-management-realm
  resource: user-service
  client-id: user-service
  client-secret: ynkrXJgeceDIow9jfIxyfjjr9oS0m6QE
  admin-username: admin-user
  admin-password: admin
  public-client: false
  bearer-only: true